// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: camera-vision.proto

package camera_vision

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CameraRequest struct {
	MAC                  string   `protobuf:"bytes,1,opt,name=MAC,proto3" json:"MAC,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CameraRequest) Reset()         { *m = CameraRequest{} }
func (m *CameraRequest) String() string { return proto.CompactTextString(m) }
func (*CameraRequest) ProtoMessage()    {}
func (*CameraRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e85839914307a646, []int{0}
}
func (m *CameraRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CameraRequest.Unmarshal(m, b)
}
func (m *CameraRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CameraRequest.Marshal(b, m, deterministic)
}
func (m *CameraRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CameraRequest.Merge(m, src)
}
func (m *CameraRequest) XXX_Size() int {
	return xxx_messageInfo_CameraRequest.Size(m)
}
func (m *CameraRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CameraRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CameraRequest proto.InternalMessageInfo

func (m *CameraRequest) GetMAC() string {
	if m != nil {
		return m.MAC
	}
	return ""
}

type CameraResponse struct {
	Info                 string   `protobuf:"bytes,1,opt,name=Info,proto3" json:"Info,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	IPAddress            string   `protobuf:"bytes,3,opt,name=IPAddress,proto3" json:"IPAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CameraResponse) Reset()         { *m = CameraResponse{} }
func (m *CameraResponse) String() string { return proto.CompactTextString(m) }
func (*CameraResponse) ProtoMessage()    {}
func (*CameraResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e85839914307a646, []int{1}
}
func (m *CameraResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CameraResponse.Unmarshal(m, b)
}
func (m *CameraResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CameraResponse.Marshal(b, m, deterministic)
}
func (m *CameraResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CameraResponse.Merge(m, src)
}
func (m *CameraResponse) XXX_Size() int {
	return xxx_messageInfo_CameraResponse.Size(m)
}
func (m *CameraResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CameraResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CameraResponse proto.InternalMessageInfo

func (m *CameraResponse) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *CameraResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CameraResponse) GetIPAddress() string {
	if m != nil {
		return m.IPAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*CameraRequest)(nil), "CameraRequest")
	proto.RegisterType((*CameraResponse)(nil), "CameraResponse")
}

func init() { proto.RegisterFile("camera-vision.proto", fileDescriptor_e85839914307a646) }

var fileDescriptor_e85839914307a646 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x4e, 0xcc, 0x4d,
	0x2d, 0x4a, 0xd4, 0x2d, 0xcb, 0x2c, 0xce, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57,
	0x52, 0xe4, 0xe2, 0x75, 0x06, 0x0b, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x09, 0x70,
	0x31, 0xfb, 0x3a, 0x3a, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0x98, 0x4a, 0x11, 0x5c,
	0x7c, 0x30, 0x25, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x42, 0x5c, 0x2c, 0x9e, 0x79, 0x69,
	0xf9, 0x50, 0x45, 0x60, 0xb6, 0x90, 0x08, 0x17, 0xab, 0x6b, 0x51, 0x51, 0x7e, 0x91, 0x04, 0x13,
	0x58, 0x10, 0xc2, 0x11, 0x92, 0xe1, 0xe2, 0xf4, 0x0c, 0x70, 0x4c, 0x49, 0x29, 0x4a, 0x2d, 0x2e,
	0x96, 0x60, 0x06, 0xcb, 0x20, 0x04, 0x8c, 0x6c, 0x61, 0x96, 0x07, 0xa7, 0x16, 0x95, 0x65, 0x26,
	0xa7, 0x0a, 0xe9, 0x70, 0x71, 0xba, 0xa7, 0x96, 0x40, 0xc4, 0x84, 0xf8, 0xf4, 0x50, 0x5c, 0x26,
	0xc5, 0xaf, 0x87, 0xea, 0x8c, 0x24, 0x36, 0xb0, 0x17, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x14, 0x14, 0xf0, 0x6b, 0xd9, 0x00, 0x00, 0x00,
}
